export const storyColumns = [
  {
    title: 'New Story',
    key: 'new-story',
    value: [
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
    ],
  },
  {
    title: 'Prioritized',
    key: 'prioritized',
    value: [
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
    ],
  },
  {
    title: 'In Progress',
    key: 'in-progress',
    value: [
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
    ],
  },
  {
    title: 'Completed',
    key: 'completed',
    value: [
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
    ],
  },
  {
    title: 'Deployed',
    key: 'deployed',
    value: [
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
      {
        description: 'Sample',
        comments: 'extra potatos',
        status: 'New Story',
        type: 'feature',
        severity: 'urgent',
        owner: 'POTATO',
      },
    ],
  },
];

export const severityList = ['Light', 'Moderate', 'Urgent'];

export const typeList = ['Feature', 'Configuration', 'Custom'];

export const inputList = {
  title: '',
  description: '',
  comments: '',
  project: '',
  type: '',
  status: '',
  severity: '',
  owner: '',
};
